### PR TITLE
Change account output from scripthash to address

### PR DESCRIPTION
**Pull request by chenzhitong**
close https://github.com/neo-project/neo-express/issues/296

### CODE REVIEW

**Comment by chenzhitong** [comment]
I can successfully compile locally, but Github Action doesn't work

**Comment by cschuchardt88** [comment]
> I can successfully compile locally, but Github Action doesn't work

Add import for `Neo.Extensions` library for `'ToHexString'` it was just moved to that library.

**Comment by chenzhitong** [comment]
> > I can successfully compile locally, but Github Action doesn't work
> 
> Add import for `Neo.Extensions` library for `'ToHexString'` it was just moved to that library.

I don't get it, I didn't add/modify the code for `ToHexString`

**Comment by cschuchardt88** [comment]
> > > I can successfully compile locally, but Github Action doesn't work
> > 
> > 
> > Add import for `Neo.Extensions` library for `'ToHexString'` it was just moved to that library.
> 
> I don't get it, I didn't add/modify the code for `ToHexString`

Workflow updates the submodule to latest. Your machine isn't updated to latest for `neo` core

**Comment by chenzhitong** [comment]
Some of the console output, although named “ScriptHash” in the code, is actually the address

**Comment by chenzhitong** [comment]
Is there anything else that needs to be changed, I checked and there is no other method that outputs what should be address but actually outputs scripthash

**Review by cschuchardt88 — APPROVED** [review]

**Comment by cschuchardt88** [comment]
I think that's all

**Pull request merged**
