### PR TITLE
NEP11/17 contract validator

### LINKED ISSUE #194: NEP11/17 contract validator
We could validate that a contract that declares that it implements NEP11 or NEP17 has an interface that conforms to the relevant standard

### PR DESCRIPTION
**Pull request by cschuchardt88**
closes #194 

Sorry closed PR by accident #311 

image

Also validates the manifest on deploy for NEP-11 or NEP-17. Checks the `SupportedStandards`

### CODE REVIEW

**Comment by cschuchardt88** [comment]
I need `neo-blockchaintoolkit-library` in this repo to complete this PR, i have to add some methods to RPC server its a custom plugin for `neo-express`.

**Comment by cschuchardt88** [comment]
Waiting to see what happens with https://github.com/neo-project/neo-devpack-dotnet/issues/812

**Comment by roman-khimov** [comment]
Notice that `tokens` and `properties` are optional, contract can omit them. And IIUC runtime checks for divisible NFT methods are not implemented yet.

It'd also be nice to add checks for `onNEPXXPayment` methods.

NeoGo compiler provides manifest checks by default (requires `--no-standards` to disable them), but it doesn't try running the contract. Internally it's implemented in this package if you're interested: https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.103.1/pkg/smartcontract/manifest/standard

**Comment by cschuchardt88** [comment]
@Ashuaidehao How you `neo-express` in Online mode?

**Comment by Ashuaidehao** [comment]
> @Ashuaidehao How you run `neo-express` in Online mode?

1. In directory A, create an "a.neo-express" file, then open a terminal run `neoxp run`, keep the terminal window running.
2. Copy "a.neo-express" to my proejct directory，then all my project's command will switch to "online-node" and process via rpc.

**Comment by cschuchardt88** [comment]
This is an ok start for now.

**Review by Liaojinghui — APPROVED** [review]

**Pull request merged**
