### PR TITLE
Added neo-express application test in actions

### LINKED ISSUE #294: Add basic regression tests to the pack and release workflows
Problem: 
We need to make sure Neo Express can run successfully after being built. 

Proposed Solution:  
- Create a test that ensures Neo Express can start the network and make a GAS or NEO transfer.
- Run tests in the build process

Related:
https://github.com/neo-project/neo-express/issues/280

### PR DESCRIPTION
**Pull request by cschuchardt88**
closes #294

### CODE REVIEW

**Comment by cschuchardt88** [comment]
Working now
image

Merge ready

**Review by lock9 — APPROVED** [review]

**Comment by cschuchardt88** [comment]
@lock9 if you want i can add tests for every command. If you want. I think that would be better but for the meantime this will do.

**Comment by lock9** [comment]
Hi @cschuchardt88,
We can increment the tests as we continue to work on the app. In the meanwhile, could you look #355 ? That is very important, and it has been inactive for a few days.

**Comment by lock9** [comment]
@Liaojinghui I think we can merge this

**Review by Liaojinghui — APPROVED** [review]

**Comment by cschuchardt88** [comment]
@lock9 still waiting for new release of neo-core to do that issue

**Pull request merged**
