### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by r41oliveira**

### CODE REVIEW

**Comment by r41oliveira** [comment]
00020126920014br.gov.bcb.pix2570qrcodes.sulcredi.coop.br/v2/v3/at/b75bb5fd-e3a6-4bd0-ab13-21dbf29a087d5204000053039865802BR5925BIGBANG_INSTITUICAO_DE_PA6009SAO_PAULO62070503***63045DD1

**Comment by r41oliveira** [comment]
USTU2408140534476871

**Comment by r41oliveira** [comment]
240814053447

**Comment by r41oliveira** [comment]
2116860471373090

**Review by cschuchardt88 — APPROVED** [review]

**Pull request merged**
