### PR TITLE
Merge visual-tracker

### PR DESCRIPTION
**Pull request by Ashuaidehao**
Close https://github.com/neo-project/neo-express/issues/374.
Need someone set `VSCODE_MARKETPLACE_TOKEN` secrets.

### CODE REVIEW

**Comment by Liaojinghui** [comment]
@Ashuaidehao do you mind to check why workflows not working?

**Comment by cschuchardt88** [comment]
@Liaojinghui haven't approved my pr #373 for development branch. You can test on your repo?

**Comment by Liaojinghui** [comment]
My bad lol.

**Comment by cschuchardt88** [comment]
@Liaojinghui `${{ secrets.MYGET_TOKEN }}` is empty for development branch.

**Comment by cschuchardt88** [comment]
Looks good to me

**Pull request merged**
