### PR TITLE
Update Neo for 3.6

### PR DESCRIPTION
**Pull request by Ashuaidehao**

### CODE REVIEW

**Comment by cschuchardt88** [comment]
it wont update to 3.6 until `neo-blockchaintoolkit-library` is updated to 3.6, Because `neo-blockchaintoolkit-library` currently uses neo 3.5 on nuget.org

**Comment by Ashuaidehao** [comment]
> it wont update to 3.6 until `neo-blockchaintoolkit-library` is updated to 3.6, Because `neo-blockchaintoolkit-library` currently uses neo 3.5 on nuget.org

I've just upgraded its version on nuget. The undone thing is how repair "worknet" compile errors, since the latest `neo-blockchaintoolkit-library` missed some code for it...

**Comment by cschuchardt88** [comment]
I dont remember the methods that were missing. But they were static methods i think extensions. maybe `ResolveFileName`

**Comment by cschuchardt88** [comment]
https://github.com/N3developertoolkit/neo-blockchaintoolkit-library/blob/d5d1a995cb5986071206d38ef639d6ce7e5856d8/src/bctklib/models/BranchInfo.cs#L27-L48

https://github.com/N3developertoolkit/neo-blockchaintoolkit-library/blob/d5d1a995cb5986071206d38ef639d6ce7e5856d8/src/bctklib/models/ToolkitWallet.cs#L33-L45

**Comment by Ashuaidehao** [comment]
> https://github.com/N3developertoolkit/neo-blockchaintoolkit-library/blob/d5d1a995cb5986071206d38ef639d6ce7e5856d8/src/bctklib/models/BranchInfo.cs#L27-L48
> 
> https://github.com/N3developertoolkit/neo-blockchaintoolkit-library/blob/d5d1a995cb5986071206d38ef639d6ce7e5856d8/src/bctklib/models/ToolkitWallet.cs#L33-L45

Thanks! I'll marge it and republish nuget.

**Comment by Ashuaidehao** [comment]
Close this PR for no push permission

**Pull request closed without merging**
