### PR TITLE
neoxp help suggests help

### LINKED ISSUE #320: neoxp help suggests help
```
$neoxp help
Specify --help for a list of available options and commands.
Unrecognized command or argument 'help'

Did you mean this?
    help
```

Feels a bit silly that it says "unrecognized 'help'" then suggest 'help'

### PR DESCRIPTION
**Pull request by cschuchardt88**
Closes #320 

**Change Log***
- Removed command suggestions.

image

### CODE REVIEW

**Comment by cschuchardt88** [comment]
I think we should remove the suggestion display from the cli. No need for it, if it displays the error message saying use `--help`.

**Comment by cschuchardt88** [comment]
I think this one display of error message is better. Let me know if you want it changed to _below_.
image

**Comment by Liaojinghui** [comment]
I will merge soon if no one against this pr.

**Comment by cschuchardt88** [comment]
Also keep in mind that i removed the  suggestions.

**Comment by lock9** [comment]
Hello,

Won't this affect all commands?

**Comment by cschuchardt88** [comment]
No, just will display this instead for invalid commands
image

**Review by Liaojinghui — APPROVED** [review]

**Pull request merged**
