### PR TITLE
Fixed pr and push and default config for projects

### PR DESCRIPTION
**Pull request by cschuchardt88**
- change workflow to not use github storage
- updated pr.yml
- update push.yml
- added development branch in workflow
- added symbol build
- remove neoxp.yml
- added neoxp to test.yml
- added step names

image
image

### CODE REVIEW

**Comment by cschuchardt88** [comment]
image

**Comment by cschuchardt88** [comment]
Please note that release will still put Artifacts files which will be big, so remember to delete it after and also you need to edit `version.json` in the root when you release new version; `remove` the `-preview`

**Comment by cschuchardt88** [comment]
@Liaojinghui Ready for review

**Comment by Liaojinghui** [comment]
Will do later.

**Review by Liaojinghui — APPROVED** [review]

**Comment by cschuchardt88** [comment]
@Liaojinghui this got overwritten when you merged development in master.

**Pull request merged**
