### PR TITLE
Combime workflow

### PR DESCRIPTION
**Pull request by cschuchardt88**
pack and publish

What this will do is:
1. Won't publish unless the `test` passes
1. Will publish on `push` and `pr`
1. Test `neoxp` application

### CODE REVIEW

**Comment by Liaojinghui** [comment]
can you also update other workflows to support development branch?

**Comment by Liaojinghui** [comment]
BTW, do we have to run pack on pr?

**Comment by cschuchardt88** [comment]
I mean yes, because `neoxp` test uses the `package` archive in the action and now that we dont have it i have to get from myget or else we remove `neoxp` test

**Comment by cschuchardt88** [comment]
image

**Comment by Liaojinghui** [comment]
> image

resolved

**Comment by Liaojinghui** [comment]
> I mean yes, because `neoxp` test uses the `package` archive in the action and now that we dont have it i have to get from myget or else we remove `neoxp` test

It has to? publish  a version for pr is not right, if someone open a malicious pr, we also publish a verison for them.

**Comment by cschuchardt88** [comment]
Ok let me close this and create new one, my upstream and fork is on different branch

**Pull request closed without merging**
