### PR TITLE
Fix the problem that double-click exe program can't be run

### PR DESCRIPTION
**Pull request by chenzhitong**
After releasing as a standalone application, beginners might run it by double-clicking directly rather than starting it from the terminal. In such cases, provide a prompt when no parameters are passed.

### CODE REVIEW

**Comment by cschuchardt88** [comment]
If we get #362 rolling. This will be a small issue

**Comment by chenzhitong** [comment]
> If we get #362 rolling. This will be a small issue

Doesn't this Issue discuss how to publish and download programs? Does this issue discuss involve program interaction?

**Comment by Jim8y** [comment]
@cschuchardt88

**Comment by cschuchardt88** [comment]
@Jim8y These will affect a lot of other tools. So I would say no. Unless @chenzhitong has a good reason.

**Comment by Jim8y** [comment]
This will not be added

**Pull request closed without merging**
