### PR TITLE
Added test workflow for basic neoxp commands

### PR DESCRIPTION
**Pull request by cschuchardt88**
**Change Log**
- Added workflow for all neoxp commands

### CODE REVIEW

**Comment by cschuchardt88** [comment]
@Liaojinghui @lock9

I need some help with the following:
- Best way to deploy the list of items _below_
- Developing the items in the list _below_

**Some things that are needed for testing are**
- Contracts
  - `NEP-11`
    - mintable (all access)
    - burnable (all access)
    - Transfer
    - non-divisible (ONLY)
  - `NEP-17`
    - mintable (all access)
    - burnable (all access)
    - Transfer
  - Basic
    - Storage
    - Events
    - Logs
    - Oracle
    - Call another contract
- batch file
  - `setup.batch`
- xUnit test for contract

**Comment by cschuchardt88** [comment]
@lock9
please check https://github.com/neo-project/neo-express/actions/runs/6900496662/job/18773817872?pr=356

See if it meets the basic needs until we get the list done.

**Comment by Liaojinghui** [comment]
> @Liaojinghui @lock9
> 
> I need some help with the following:
> 
> * Best way to deploy the list of items _below_
> * Developing the items in the list _below_
> * Make issues for the list _below_ (one of you two please)
> 
> **Some things that are needed for testing are**
> 
> * Contracts
>   
>   * `NEP-11`
>     
>     * mintable (all access)
>     * burnable (all access)
>     * Transfer
>     * non-divisible (ONLY)
>   * `NEP-17`
>     
>     * mintable (all access)
>     * burnable (all access)
>     * Transfer
>   * Basic
>     
>     * Storage
>     * Events
>     * Logs
>     * Oracle
>     * Call another contract
> * batch file
>   
>   * `setup.batch`
> * xUnit test for contract

What you mean by this?

**Comment by cschuchardt88** [comment]
I want to test all the command in `neo-express` application in github actions. And i need those things.

I need those contracts created and in addition

 I need a contract xunit test see for more detail of what im talking about #322

Also i need someone to create a batch file for the `neo-express`

If not i guess i could do it all...

**Comment by Liaojinghui** [comment]
I'll see what I can do, but not sure.

**Comment by Liaojinghui** [comment]
Test contracts:

https://github.com/neo-project/neo-devpack-dotnet/tree/master/tests/Neo.SmartContract.Framework.UnitTests/TestClasses

https://github.com/neo-project/examples/tree/master/csharp

**Comment by cschuchardt88** [comment]
@Liaojinghui either way this ready to go for now, just have the basics. Which is good enough for now. The more advanced stuff I'll add later

**Comment by cschuchardt88** [comment]
this one is ready

**Comment by Liaojinghui** [comment]
@cschuchardt88 I know its not relavent, but can you please delete all artifact upload logic and download logic and push to azure logic and change the package direction to myget? I need someone else to do it such that I can merge.

**Review by Liaojinghui — APPROVED** [review]

**Comment by cschuchardt88** [comment]
@Liaojinghui whats the myget link? ngd one?

**Comment by Liaojinghui** [comment]
Can we do with this one? 

run: dotnet nuget push out/*.nupkg -s https://www.myget.org/F/neo/api/v2/package -k ${MYGET_TOKEN} -ss https://www.myget.org/F/neo/symbols/api/v2/package -sk ${MYGET_TOKEN}

**Pull request merged**
