### PR TITLE
Changed `file_header` to use `{fileName}`

### PR DESCRIPTION
**Pull request by cschuchardt88**
This update is to clean up the file header wording. Now uses filename instead of `neo`. 

Also changed each `*.cs` file to reflect this change.

**Change Log**
- Add filenames to the file header of each *.cs file
- Added missing file headers
- Added requirement for file header on build

```.editorconfig
# Require file header
dotnet_diagnostic.IDE0073.severity = error
```

### CODE REVIEW

**Comment by Liaojinghui** [comment]
There would be no need. We just need to let people know it's MIT license. And this version of copyright header is from the founder, we should not change it without a solid reason.

**Comment by cschuchardt88** [comment]
Well normally you replace part of the message to indicate a filename or project. For example we manually change the message to reflect the project name (*.csproj) file in the `node-modules` repo. 

```
// The Neo.Plugins.ApplicationLogs is free software distributed under the MIT software license,
...
```

Also i added this file header, Just copied it from existing `neo` repo. Just forgot to update the project name to `{fileName}`

**Comment by cschuchardt88** [comment]
Than we can keep the way it is. Just doesn't make sense `The neo is a free software`. 

Well what do you propose?

**Comment by Liaojinghui** [comment]
> Well what do you propose?

xxx file belongs xxx project,,,, or something more reasonable, instead of xxx file is a project

**Comment by cschuchardt88** [comment]
Hows this

```csharp
// Copyright (C) 2015-2023 The Neo Project.
//
// Program.cs file belongs to neo-express project and is free
// software distributed under the MIT software license, see the
// accompanying file LICENSE in the main directory of the
// repository or http://www.opensource.org/licenses/mit-license.php
// for more details.
//
// Redistribution and use in source and binary forms with or without
// modifications are permitted.
```

**Comment by Liaojinghui** [comment]
LGTM

**Review by Liaojinghui — APPROVED** [review]

**Pull request merged**
