### PR TITLE
Update Neo for 3.6

### PR DESCRIPTION
**Pull request by Ashuaidehao**

### CODE REVIEW

**Review by steven1227 — APPROVED** [review]

**Comment by gsmachado** [comment]
@Ashuaidehao test are passing?

**Comment by Ashuaidehao** [comment]
> @Ashuaidehao tests are passing? I can't access the GitHub Action logs anymore.

Waiting https://www.nuget.org/packages/Neo.BlockchainToolkit.Library upgrade to v3.6. Since github action couldn't load the right version lib for now, you can manually add the [nupkg file](https://github.com/N3developertoolkit/neo-blockchaintoolkit-library/releases) to your load source for test.

**Comment by cschuchardt88** [comment]
have you looked at github action log on that repo

```
Run actions/setup-dotnet@v3
/home/runner/work/_actions/actions/setup-dotnet/v3/externals/install-dotnet.sh --channel 7.0
dotnet-install: .NET Core SDK with version '7.0.401' is already installed.
dotnet-auth: Finding any source references in /home/runner/work/neo-blockchaintoolkit-library/neo-blockchaintoolkit-library/nuget.config, writing a new temporary configuration file with credentials to /home/runner/work/neo-blockchaintoolkit-library/nuget.config
Error: The NUGET_AUTH_TOKEN environment variable was not provided. In this step, add the following: 
env:
  NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Dont think it coming.

**Review by superboyiii — APPROVED** [review]

**Comment by lock9** [comment]
If this PR has two approvals, why can't it be merged?

**Review by lock9 — APPROVED** [review]

**Review by Liaojinghui — APPROVED** [review]

**Comment by Liaojinghui** [comment]
> If this PR has two approvals, why can't it be merged?

Well, i was waiting for others to merge it, turns out i am the one who has the right to merge it....

**Pull request merged**
