### PR TITLE
standalone application

### LINKED ISSUE #355: Update the github workflow to produce and distribute Neo Express as a standalone application
**Is your feature request related to a problem? Please describe.**
We need to ship the neo-express executable. The current workflow doesn't generate or publish the executables. 

Related to #268 

**Describe the solution you'd like**
Update the workflow file to generate and publish the executables here on GitHub

**Additional context**
@cschuchardt88 seems experienced enough to deal with this, so I suggest he works on it

### PR DESCRIPTION
**Pull request by cschuchardt88**
Closes #355

**Change Log**
- Updated to `neo` 3.6.2 - to work in standalone mode
- Changed method to reflect `neo` 3.6.2

Release Directory
image

### CODE REVIEW

**Comment by cschuchardt88** [comment]
@lock9 @Liaojinghui 
check this to make sure i meet your needs. Note not done yet but its a start...
https://github.com/neo-project/neo-express/actions/runs/6903046496/job/18780948358?pr=357

**Comment by cschuchardt88** [comment]
**Building for:**
- osx-x64 (Minimum OS version is macOS 10.12 Sierra)
- osx-arm64
- linux-x64 (Most desktop distributions like CentOS, Debian, Fedora, Ubuntu, and derivatives)
- linux-musl-arm64 (Used to build Docker images for 64-bit Arm v8 and minimalistic base images)
- linux-arm64 (Linux distributions running on 64-bit Arm like Ubuntu Server 64-bit on Raspberry Pi Model 3+)
- win-x64
- win-x86
- win-arm64

**Review by Liaojinghui — APPROVED** [review]

**Comment by Liaojinghui** [comment]
Call me to merge if good to go.

**Comment by cschuchardt88** [comment]
wait a sec.... please

**Comment by Liaojinghui** [comment]
> wait a sec.... please

Wont merge until called. Too rush in the past.

**Comment by cschuchardt88** [comment]
Keep in mind standalone build takes like +10 mins. May need to split in different VMs?

**Comment by Liaojinghui** [comment]
Maybe not make it build on pr?

**Comment by cschuchardt88** [comment]
@Liaojinghui ok removed, is there a way for me to check the azure Artifacts?

**Comment by Liaojinghui** [comment]
> @Liaojinghui ok removed, is there a way for me to check the azure Artifacts?

I mean maybe build on release only, will it be called on release?

**Comment by Liaojinghui** [comment]
> @Liaojinghui is there way you can test release?

I can trigger the release action, that is all i can do, not sure if that is what you need.

**Comment by cschuchardt88** [comment]
image
image

I can't test mac, can someone test? `Rocksdb` doesn't support `arm` and `x86` CPUs

Working:
- Windows x64
- Linux x64

**Comment by cschuchardt88** [comment]
ok good for look over

**Comment by Liaojinghui** [comment]
Uncomment the release check?

**Comment by Ashuaidehao** [comment]
> > @Liaojinghui ok removed, is there a way for me to check the azure Artifacts?
> 
> I mean maybe build on release only, will it be called on release? As to the artifacts, @Ashuaidehao

It's private now, that's why I post https://github.com/neo-project/neo-express/issues/319.

**Comment by cschuchardt88** [comment]
@Ashuaidehao so build standalone on release only? atm it's push and release

**Comment by Liaojinghui** [comment]
@superboyiii do you get the permission now?

**Review by cschuchardt88 — COMMENTED** [review]
OK finished @Ashuaidehao can you review?

**Review by lock9 — CHANGES_REQUESTED** [review]
- It's missing the arm64 builds
- On macOS, you need to sign the binaries using codesign. I think this can only be done using a macOS device
  - Please check this: https://github.com/dotnet/runtime/issues/79267

**Comment by Ashuaidehao** [comment]
> @Ashuaidehao so build standalone on release only? atm it's push and release

Yes, I prefer to build standalone on release only, it costs too much time on each PR.

**Comment by cschuchardt88** [comment]
> * It's missing the arm64 builds
> * On macOS, you need to sign the binaries using codesign. I think this can only be done using a macOS device
>   
>   * Please check this: [Running .NET 7 single file binary on Apple M1 chip causes app to be "killed" dotnet/runtime#79267](https://github.com/dotnet/runtime/issues/79267)

I tried arm64, not osx but `rockdb` doesn't work on arm, im pretty sure. Unless someone wants to test again. Also doesn't work on x86 ... no binaries.

**Comment by lock9** [comment]
It does, I've tested it

**Comment by cschuchardt88** [comment]
@lock9 what were the steps that you took to build it? I can build it. But i can't run it. I think it's too big to upload here.

**Comment by cschuchardt88** [comment]
I can't test osx github action locally. Because it uses osx VM and the app im using doesn't support. Only supports linux github action VMs. But we can run the `release` action to see if it fails?

**Comment by cschuchardt88** [comment]
@lock9 Can you test osx build? I made this with actions in my repo. 😀 

https://github.com/cschuchardt88/neo-express/releases/tag/3.6.79-preview-g1b35c39638

**Comment by cschuchardt88** [comment]
Sorry have to close messed up this PR branch in my repo.

**Comment by Liaojinghui** [comment]
> @Liaojinghui But we can run the `release` action to see if it fails? Better yet run workflow standalone?

Lets wait for @superboyiii  to do it, running the release action for me requires to merge it to a release branch first.

**Comment by cschuchardt88** [comment]
@Liaojinghui it's here now #358 and i tested in my github repo so working great 100% complete. But only if it meets your needs.

**Pull request closed without merging**
